version: '3.8'

services:
  rule-engine-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo      # Ensures the MongoDB service is started before the backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
